//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextDay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetails
    {
        public string DocumentType { get; set; }
        public string Document { get; set; }
        public string DocumentVersion { get; set; }
        public int Sequence { get; set; }
        public string Item { get; set; }
        public string ItemType { get; set; }
        public string ProductType { get; set; }
        public string ProductTypeCategory { get; set; }
        public string Description { get; set; }
        public string Memo { get; set; }
        public string Size { get; set; }
        public float OrderQty { get; set; }
        public float ShipQty { get; set; }
        public float AdjustedQty { get; set; }
        public float Discount { get; set; }
        public decimal UnitList { get; set; }
        public decimal UnitNet { get; set; }
        public string Taxes { get; set; }
        public decimal Tax1 { get; set; }
        public decimal Tax2 { get; set; }
        public decimal Tax3 { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitCostLabor { get; set; }
        public decimal ExtendedNet { get; set; }
        public decimal ExtendedNetTaxed { get; set; }
        public decimal ExtendedCost { get; set; }
        public Nullable<bool> NonStockingFlag { get; set; }
        public bool SerializedFlag { get; set; }
        public Nullable<bool> TemporaryPriceFlag { get; set; }
        public string Serviceperson { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string ServiceRequired { get; set; }
        public string ServicePerformed { get; set; }
        public float ServiceHoursActual { get; set; }
        public float ServiceHoursChargeable { get; set; }
        public string StockingPoint { get; set; }
        public string Grouping { get; set; }
        public Nullable<bool> CasingCredit { get; set; }
        public string CasingGrade { get; set; }
        public string CasingManufacturer { get; set; }
        public string CasingID { get; set; }
        public Nullable<bool> WarrantyFlag { get; set; }
        public short WarrantyPercentRemaining { get; set; }
        public decimal WarrantyReplacementCost { get; set; }
        public string WarrantyCustomer { get; set; }
        public Nullable<int> HeaderRowID { get; set; }
        public string HeaderType { get; set; }
        public string ReminderServiceCode { get; set; }
        public int OrderRowID { get; set; }
        public int OrderDetailRowID { get; set; }
        public float OvertimeFactor { get; set; }
        public bool Completed { get; set; }
        public int PODetailRowID { get; set; }
        public string Supplier { get; set; }
        public bool DepositProcessed { get; set; }
        public int RowID { get; set; }
        public string TranslatedDescription { get; set; }
        public string TranslatedServicePerformed { get; set; }
        public string WarrantyCode { get; set; }
        public string ItemGLAccount { get; set; }
        public string Reference { get; set; }
        public Nullable<bool> CasingToInventory { get; set; }
        public Nullable<int> LineItemNumber { get; set; }
        public string DiscountPlan1 { get; set; }
        public Nullable<float> DiscountPlan1Percentage { get; set; }
        public string DiscountPlan1Method { get; set; }
        public Nullable<decimal> DiscountPlan1Amount { get; set; }
        public string DiscountPlan2 { get; set; }
        public Nullable<float> DiscountPlan2Percentage { get; set; }
        public string DiscountPlan2Method { get; set; }
        public Nullable<decimal> DiscountPlan2Amount { get; set; }
        public string DiscountPlan3 { get; set; }
        public Nullable<float> DiscountPlan3Percentage { get; set; }
        public string DiscountPlan3Method { get; set; }
        public Nullable<decimal> DiscountPlan3Amount { get; set; }
        public string RebillTo { get; set; }
        public Nullable<int> CreditRowID { get; set; }
        public Nullable<int> FollowupRun { get; set; }
        public string Manufacturer { get; set; }
        public string UnitMeasure { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string DetailCreditReason { get; set; }
        public string PriceSource { get; set; }
        public Nullable<bool> FixedPrice { get; set; }
        public Nullable<bool> FixedQty { get; set; }
        public string SupplierName { get; set; }
        public string SupplierItem { get; set; }
        public string WarrantyReason { get; set; }
        public string RefusalReason { get; set; }
        public Nullable<int> ActivantCategoryNumber { get; set; }
        public Nullable<int> ActivantGroupNumber { get; set; }
        public Nullable<int> ActivantOperation { get; set; }
        public Nullable<int> ActivantOperationTail { get; set; }
        public Nullable<System.DateTime> SaleBegins { get; set; }
        public Nullable<System.DateTime> SaleEnds { get; set; }
        public string ServicePerson2 { get; set; }
        public string ServicePerson3 { get; set; }
        public string ServicePerson4 { get; set; }
        public Nullable<System.DateTime> ServiceDate2 { get; set; }
        public Nullable<System.DateTime> ServiceDate3 { get; set; }
        public Nullable<System.DateTime> ServiceDate4 { get; set; }
        public Nullable<float> ServiceHoursActual2 { get; set; }
        public Nullable<float> ServiceHoursActual3 { get; set; }
        public Nullable<float> ServiceHoursActual4 { get; set; }
        public Nullable<System.Guid> RowGUID { get; set; }
        public Nullable<System.Guid> AuthorizationRowGUID { get; set; }
        public Nullable<float> MaximumQty { get; set; }
        public string ActivantPartDescription { get; set; }
        public string PromotionCode { get; set; }
        public string PromotionDescription { get; set; }
        public Nullable<decimal> OriginalUnitList { get; set; }
        public string LaborCategory { get; set; }
        public string LaborSubcategory { get; set; }
        public Nullable<decimal> OriginalUnitNet { get; set; }
        public Nullable<decimal> Min_UnitNet { get; set; }
        public Nullable<int> CopiedFromRowID { get; set; }
        public Nullable<int> AddedFromRowID { get; set; }
        public Nullable<bool> HoldForDelivery { get; set; }
        public string SupplierLocation { get; set; }
        public Nullable<decimal> AllocatedHours { get; set; }
        public string ComebackType { get; set; }
        public Nullable<int> NextReminderInWeeks { get; set; }
    }
}
