//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextDay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTypes
    {
        public string Type { get; set; }
        public string Caption { get; set; }
        public Nullable<bool> CashierRequired { get; set; }
        public float InventoryDirection { get; set; }
        public float AccountingSign { get; set; }
        public Nullable<bool> UpdateSalesHistory { get; set; }
        public string Comments { get; set; }
        public string Code { get; set; }
        public bool CustomerRequired { get; set; }
        public bool CashCustomerAllowed { get; set; }
        public string Styles { get; set; }
        public string StyleDefaults { get; set; }
        public string TranslatedCode { get; set; }
        public bool ShowVehicle { get; set; }
        public bool AllowLabor { get; set; }
        public bool AllowNegativeQtys { get; set; }
        public bool CheckStockButton { get; set; }
        public bool IsPricedAtCost { get; set; }
        public bool PickButton { get; set; }
        public bool SwitchToCustomerBranch { get; set; }
    }
}
